version: "3.8"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_ENABLED=true
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000" # Grafana UI ở http://localhost:3001
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
  k6:
    image: grafana/k6
    depends_on:
      - influxdb
    volumes:
      - ./test-booking.js:/scripts/test-booking.js
    command: run --out influxdb=http://influxdb:8086/k6 /scripts/test-booking.js

volumes:
  influxdb-data:
  grafana-data:
